### PR TITLE
fix(stageleft): properly handle `crate::` imports

### LINKED ISSUE #1092: Make sure that stageleft can handle `super` and `crate` references
Our trick of importing the scope will definitely not work when a `super` or `crate` is spliced into the output code. We need to replace it with a fully-qualified module path instead.

### PR DESCRIPTION
**Pull request by shadaj**
Fixes #1092

### CODE REVIEW

File: stageleft_tool/src/lib.rs [hunk 1]
```diff
@@ -144,6 +144,22 @@ impl VisitMut for GenFinalPubVistor {
...
+        if i.ident == "crate" {
+            *i = UsePath {
+                ident: syn::Ident::new("crate", Span::call_site()),
+                colon2_token: Default::default(),
+                tree: Box::new(syn::UseTree::Path(UsePath {
+                    ident: parse_quote!(__staged),
+                    colon2_token: Default::default(),
+                    tree: i.tree.clone(),
+                })),
+            };
```
Comment (MingweiSamuel) [inline stageleft_tool/src/lib.rs:157]: Could this just be
```rust
i.tree = Box::new(syn::UseTree::Path(UsePath {
    ident: parse_quote!(__staged),
    colon2_token: Default::default(),
    tree: i.tree.clone(),
}));
```

**Review by MingweiSamuel — APPROVED** [review]
