### PR TITLE
fix: unify antijoin and difference with set and multiset semantics

### LINKED ISSUE #827: add `_multiset` variants to all join types
`anti_join_multiset`
`cross_join_multiset`

### PR DESCRIPTION
**Pull request by jhellerstein**
Fixes #827 with multiset variants of antijoin and difference.
- `anti_join` rewritten in the style of `join`
- `anti_join_multiset` is a simpler version of `anti_join` 
- `difference` now reuses the logic of `anti_join`
- `difference_multiset` reuses the logic of `anti_join_multiset`

Also adds `cross_join_multiset` as well, reusing logic of of `join_multiset`.

In future it would be nice to clean this up further with macros:
1. replace the `difference` operators with macros over `antijoin`, so the `pos` side of `difference` as well as the output of `antijoin` are rewritten as:
```
... -> map(|k| (k, ()) -> [pos]my_antijoin;
my_antijoin = antijoin() -> map(|(k, v)| k)
```
2. replace the `antijoin` operator with a macro using `unique` and `antijoin_multiset`, so the `pos` side of `antijoin` is rewritten as:
```
... -> unique() -> [pos]my_antijoin_multiset
my_antijoin_multiset = antijoin_multiset()
```

### CODE REVIEW

File: hydroflow_lang/src/graph/ops/difference_multiset.rs [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+            write_iterator,
+            write_iterator_after,
+        })
+    },
+    };
+
+
+
+
+//     write_fn: |wc @ &WriteContextArgs {
```
Comment (zzlk) [inline hydroflow_lang/src/graph/ops/difference_multiset.rs:88]: delete this commented out code

File: hydroflow_lang/src/graph/ops/difference_multiset.rs [hunk 2]
```diff
@@ -0,0 +1,183 @@
...
+                           ident,
+                           inputs,
+                           op_inst:
+                               OperatorInstance {
+                                   ..
+                               },
+                           ..
+                       },
+                       diagnostics| {
+        let wc = WriteContextArgs {
```
Comment (zzlk) [inline hydroflow_lang/src/graph/ops/difference_multiset.rs:59]: i don't think you need to construct a new wc since you aren't modifying anything in it. I think you can delete lines 59 to 62 here.

File: hydroflow_lang/src/graph/ops/difference.rs [hunk 3]
```diff
@@ -47,98 +46,138 @@ pub const DIFFERENCE: OperatorConstraints = OperatorConstraints {
...
-                    &*format!(
-                        "Unexpected persistence arguments for difference, expected two arguments with the first as `'tick`, got {:?}", // or whatever
-                        other
-                    ),
-                ));
-
-                Persistence::Tick
-            }
+                       diagnostics| {
+        let wc = WriteContextArgs {
```
Comment (zzlk) [inline hydroflow_lang/src/graph/ops/difference.rs:59]: I think you can delete lines 59 to 62 here

File: hydroflow_lang/src/graph/ops/anti_join_multiset.rs [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+                }
+            };
+            Ok((antijoindata_ident, borrow_ident, init, borrow))
+        };
+
+        let (neg_antijoindata_ident, neg_borrow_ident, neg_init, neg_borrow) =
+                make_antijoindata(persistences[1], "neg")?;
+
+        let write_prologue = quote_spanned! {op_span=>
+            let #neg_antijoindata_ident = #hydroflow.add_state(std::cell::RefCell::new(
```
Comment (zzlk) [inline hydroflow_lang/src/graph/ops/anti_join_multiset.rs:114]: `persistences[0]` is never referenced in this code so how can `'static` persistence on the pos side work?

Comment (zzlk) [reply hydroflow_lang/src/graph/ops/anti_join_multiset.rs:114]: should also add a test for that case too.

File: hydroflow_lang/src/graph/ops/anti_join_multiset.rs [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+                        neg_state: &'a mut #root::rustc_hash::FxHashSet<K>,
+                    ) -> impl 'a + Iterator<Item = (K, V)>
+                    where
+                        K: Eq + ::std::hash::Hash + Clone,
+                        V: Eq + ::std::hash::Hash + Clone,
+                        I1: 'a + Iterator<Item = K>,
+                        I2: 'a + Iterator<Item = (K, V)>,
+                    {
+                        neg_state.extend(input_neg);
+                        input_pos.filter_map(move |x| {
```
Comment (zzlk) [inline hydroflow_lang/src/graph/ops/anti_join_multiset.rs:139]: is this equivalent to `input_pos.filter(|x| !neg_state.contains(&x.0))`?

File: hydroflow_lang/src/graph/ops/anti_join.rs [hunk 6]
```diff
@@ -50,44 +51,110 @@ pub const ANTI_JOIN: OperatorConstraints = OperatorConstraints {
...
-                        V: Eq + Clone,
-                        I1: 'a + Iterator<Item = (K, V)>,
-                        I2: 'a + Iterator<Item = K>,
+                        V: Eq + ::std::hash::Hash + Clone,
+                        I1: 'a + Iterator<Item = K>,
+                        I2: 'a + Iterator<Item = (K, V)>,
                     {
-                        borrow_state.extend(input_neg);
-                        input_pos.filter(move |x| !borrow_state.contains(&x.0))
+                        neg_state.extend(input_neg);
```
Comment (zzlk) [inline hydroflow_lang/src/graph/ops/anti_join.rs:141]: I think you don't need any of the mapping functionality of `filter_map` and `filter` would be fine to use here.

File: hydroflow_lang/src/graph/ops/difference_multiset.rs (hunk 2 above)
Comment (jhellerstein) [reply hydroflow_lang/src/graph/ops/difference_multiset.rs:59]: Good catch. Also applied to `difference.rs` now.

File: hydroflow_lang/src/graph/ops/anti_join.rs [hunk 7]
```diff
@@ -50,48 +52,125 @@ pub const ANTI_JOIN: OperatorConstraints = OperatorConstraints {
...
+
+                        #root::compiled::pull::AntiJoin::new_from_mut(input_pos, neg_state, pos_state, is_new_tick)
                     }
 
+                    let __is_new_tick = {
+                        let mut __borrow_ident = #context.state_ref(#tick_ident).borrow_mut();
+
+                        if *__borrow_ident <= #context.current_tick() {
+                            *__borrow_ident = #context.current_tick() + 1;
+                            // new tick
```
Comment (jhellerstein) [inline hydroflow_lang/src/graph/ops/anti_join.rs:155]: @zzlk There was a bug here previously and this seems to work but it's different than what you put now in `join.rs`. Can you please align?
