### PR TITLE
fix(hydroflow): add `add_state_tick` to state API, reset at end of each tick, fix #1298

### LINKED ISSUE #1298: Singletons may reference `'tick` stateful operator state that wasn't reset for the tick (due to the subgraph not being scheduled), resulting in incorrect behavior
## Quick fix options:
1. Add a tick hook to the scheduler
    * driven by scheduler, very general
    * eager
    * either (A) end-of-tick (before external events), or (B) start-of-tick (after external events)
2. Add lifetimes to the state API in `Context` (reset all `'tick` state at the start of tick)
    * driven by scheduler, would be specific feature for state API
    * eager
    * either (A) end-of-tick, or (B) start-of-tick
3. Wrap all `'tick` state in a wrapper that checks if it is a new tick and the state needs to be cleared
    * driven by caller: so the singleton referencer will end up clearing the state when it grabs it
    * would require a slight change to the singleton code substitution
    * lazy
    
### Question: When should data actually be cleared? Eagerly or lazily?
1. Eagerly: Between ticks (at the change to the new tick)
2. Lazily: When it is used

## Bug example

In this case, if the left sg_1v1 runs but the sg_2v1 doesn't, then the left state doesn't get cleared (even though it should because it is `'tick`.

```mermaid
%%{init:{'theme':'base','themeVariables':{'clusterBkg':'#ddd','clusterBorder':'#888'}}}%%
flowchart TD
classDef pullClass fill:#8af,stroke:#000,text-align:left,white-space:pre
classDef pushClass fill:#ff8,stroke:#000,text-align:left,white-space:pre
classDef otherClass fill:#fdc,stroke:#000,text-align:left,white-space:pre
linkStyle default stroke:#aaa
1v1[\"(1v1) <code>source_stream(lhs_recv)</code>"/]:::pullClass
2v1[\"(2v1) <code>map(SetUnionSingletonSet::new_from)</code>"/]:::pullClass
3v1[\"(3v1) <code>state::&lt;'tick, SetUnionHashSet&lt;u32&gt;&gt;()</code>"/]:::pullClass
4v1[\"(4v1) <code>source_stream(rhs_recv)</code>"/]:::pullClass
5v1[\"(5v1) <code>map(SetUnionSingletonSet::new_from)</code>"/]:::pullClass
6v1[\"(6v1) <code>state::&lt;'tick, SetUnionHashSet&lt;u32&gt;&gt;()</code>"/]:::pullClass
7v1[\"(7v1) <code>lattice_bimorphism(CartesianProductBimorphism::&lt;HashSet&lt;_&gt;&gt;::default(), lhs, rhs)</code>"/]:::pullClass
8v1[\"(8v1) <code>lattice_reduce()</code>"/]:::pullClass
9v1[\"(9v1) <code>inspect(|x| println!(&quot;{:?}: {:?}&quot;, context.current_tick(), x))</code>"/]:::pullClass
10v1[/"(10v1) <code>for_each(|x| out_send.send(x).unwrap())</code>"\]:::pushClass
11v1["(11v1) <code>handoff</code>"]:::otherClass
12v1["(12v1) <code>handoff</code>"]:::otherClass
13v1["(13v1) <code>handoff</code>"]:::otherClass
2v1-->3v1
1v1-->2v1
5v1-->6v1
4v1-->5v1
3v1==>|items|11v1; linkStyle 4 stroke:#060
6v1==>|items|12v1; linkStyle 5 stroke:#060
9v1==>10v1; linkStyle 6 stroke:#060
8v1==>9v1; linkStyle 7 stroke:#060
7v1==>13v1; linkStyle 8 stroke:#060
11v1==>|0|7v1; linkStyle 9 stroke:#060
12v1==>|1|7v1; linkStyle 10 stroke:#060
13v1==>8v1; linkStyle 11 stroke:#060
3v1--x7v1; linkStyle 12 stroke:red
6v1--x7v1; linkStyle 13 stroke:red
subgraph sg_1v1 ["sg_1v1 stratum 0"]
    1v1
    2v1
    3v1
    subgraph sg_1v1_var_lhs ["var <tt>lhs</tt>"]
        1v1
        2v1
        3v1
    end
end
subgraph sg_2v1 ["sg_2v1 stratum 0"]
    4v1
    5v1
    6v1
    subgraph sg_2v1_var_rhs ["var <tt>rhs</tt>"]
        4v1
        5v1
        6v1
    end
end
subgraph sg_3v1 ["sg_3v1 stratum 1"]
    7v1
    subgraph sg_3v1_var_my_join ["var <tt>my_join</tt>"]
        7v1
    end
end
subgraph sg_4v1 ["sg_4v1 stratum 1"]
    8v1
    9v1
    10v1
    subgraph sg_4v1_var_my_join ["var <tt>my_join</tt>"]
        8v1
        9v1
        10v1
    end
end
```

```rust
use std::collections::HashSet;

use hydroflow::util::collect_ready;
use hydroflow::{assert_graphvis_snapshots, hydroflow_syntax};
use lattices::set_union::{CartesianProductBimorphism, SetUnionHashSet, SetUnionSingletonSet};
use multiplatform_test::multiplatform_test;

#[multiplatform_test]
pub fn test_cartesian_product() {
    let (lhs_send, lhs_recv) = hydroflow::util::unbounded_channel::<u32>();
    let (rhs_send, rhs_recv) = hydroflow::util::unbounded_channel::<u32>();
    let (out_send, mut out_recv) = hydroflow::util::unbounded_channel::<_>();

    let mut df = hydroflow_syntax! {
        lhs = source_stream(lhs_recv)
            -> map(SetUnionSingletonSet::new_from)
            -> state::<'tick, SetUnionHashSet<u32>>();
        rhs = source_stream(rhs_recv)
            -> map(SetUnionSingletonSet::new_from)
            -> state::<'tick, SetUnionHashSet<u32>>();

        lhs[items] -> [0]my_join;
        rhs[items] -> [1]my_join;

        my_join = lattice_bimorphism(CartesianProductBimorphism::<HashSet<_>>::default(), #lhs, #rhs)
            -> lattice_reduce()
            -> inspect(|x| println!("{:?}: {:?}", context.current_tick(), x))
            -> for_each(|x| out_send.send(x).unwrap());
    };
    assert_graphvis_snapshots!(df);

    for x in 0..3 {
        lhs_send.send(x).unwrap();
    }
    for x in 3..5 {
        rhs_send.send(x).unwrap();
    }
    df.run_available();
    assert_eq!(
        &[SetUnionHashSet::new(HashSet::from_iter([
            (0, 3),
            (0, 4),
            (1, 3),
            (1, 4),
            (2, 3),
            (2, 4),
        ]))],
        &*collect_ready::<Vec<_>, _>(&mut out_recv)
    );

    for x in 3..5 {
        lhs_send.send(x).unwrap();
    }
    df.run_available();
    let out = collect_ready::<Vec<_>, _>(&mut out_recv);
    assert_eq!(0, out.len(), "expected empty, got: {:?}", out);
}
```

### PR DESCRIPTION
**Pull request by MingweiSamuel**
Option 2 of #1298

### CODE REVIEW

**Comment by MingweiSamuel** [comment]
Main feature in the title is in `src/scheduled/{context,graph}.rs`
Codegen for some stateful operators (those which can be used as singletons, and some others) is changed to use the new API.
Add a test `test_cartesian_product_tick_state` for #1298
Rest of the diff is snapshot changes

File: hydroflow/src/scheduled/context.rs [hunk 1]
```diff
@@ -188,3 +206,40 @@ impl Context {
...
+        }
+    }
+}
+
+/// Internal struct containing a pointer to [`Hydroflow`]-owned state.
+struct StateData {
+    state: Box<dyn Any>,
+    tick_reset: Option<TickResetFn>,
+}
+type TickResetFn = Box<dyn FnMut(&mut dyn Any)>;
```
Comment (rohitkulshreshtha) [inline hydroflow/src/scheduled/context.rs:245]: This could use some documentation.
1. What is the use of a TickResetFn?
2. Who provides it? 
3. Who calls it? When?

File: hydroflow_lang/src/graph/ops/persist.rs [hunk 2]
```diff
@@ -46,6 +46,10 @@ pub const PERSIST: OperatorConstraints = OperatorConstraints {
     persistence_args: RANGE_0,
     type_args: RANGE_0,
     is_external_input: false,
+    // If this is set to true, the state will need to be cleared using `#context.set_state_tick_hook`
+    // to prevent reading uncleared data if this subgraph doesn't run.
+    // https://github.com/hydro-project/hydroflow/issues/1298
+    // If `'tick` lifetimes are added.
```
Comment (rohitkulshreshtha) [inline hydroflow_lang/src/graph/ops/persist.rs:52]: Are we using the singleton feature as a proxy signal to indicate that the state needs to be clear for a tick?

For example, could there ever be a non-singleton-related state that may need clearing?

Comment (MingweiSamuel) [reply hydroflow_lang/src/graph/ops/persist.rs:52]: Yeah. Other `'tick` state will need to be cleared, but existing implementation does that when the iterator runs, which is good enough. There is only a problem if a singleton can reference the state before the iterator runs, in that case.

**Review by rohitkulshreshtha — APPROVED** [review]
Awesome.
