### PR TITLE
fix(hydroflow): improve type inference for fold accumulators

### LINKED ISSUE #985: Type-inference fails for element parameter to a fold closure
```rust
#[multiplatform_test]
pub fn test_fold_inference() {
    let (items_send, items_recv) = hydroflow::util::unbounded_channel::<String>();

    let mut df = hydroflow::hydroflow_syntax! {
        source_stream(items_recv)
            -> fold::<'tick>(|| 0, |old, s| { old += s.len() })
            -> for_each(|v: usize| {});
    };
}
```

Type inference fails for the `s` parameter (and somehow is not an issue for `old`!). Seems like this is a case that should work.

### PR DESCRIPTION
**Pull request by shadaj**
fix(hydroflow): improve type inference for fold accumulators

Fixes #985

### CODE REVIEW

File: hydroflow/tests/surface_fold.rs [hunk 1]
```diff
@@ -163,3 +163,16 @@ pub fn test_fold_sort() {
...
+pub fn test_fold_inference() {
+    let (_items_send, items_recv) = hydroflow::util::unbounded_channel::<String>();
+
+    let df = hydroflow::hydroflow_syntax! {
+        source_stream(items_recv)
+            -> fold::<'tick>(|| 0, |old, s| { *old += s.len() })
+            -> for_each(|_| {});
+    };
+
+    assert_graphvis_snapshots!(df);
```
Comment (MingweiSamuel) [inline hydroflow/tests/surface_fold.rs:177]: `let _ = df;` for the warning

File: hydroflow_lang/src/graph/ops/fold.rs
Comment (MingweiSamuel) [inline hydroflow_lang/src/graph/ops/fold.rs:1]: Would be nice to give the single letter type and argument parameters more descriptive names later

**Review by MingweiSamuel — APPROVED** [review]
