### PR TITLE
fix(stageleft): handle multiple references to copy-able free variables

### LINKED ISSUE #1103: Stageleft sometimes double-captures a referenced value
Need to dig up the concrete snippet, @davidchuyaya ran into this where referencing a `RuntimeData<&'a ...>` twice inside a `q!` (once outside and once inside a closure). This results in a compilation error due to an attempt to splice the referenced value twice, but the second splice processes the fake value returned by the first splice.

### PR DESCRIPTION
**Pull request by shadaj**
fix(stageleft): handle multiple references to copy-able free variables

Fixes #1103

### CODE REVIEW

**Comment by shadaj** [comment]
Also partially fixes #1122

File: stageleft_macro/src/quote_impl/free_variable/mod.rs [hunk 1]
```diff
@@ -115,27 +115,30 @@ impl<'ast> syn::visit::Visit<'ast> for FreeVariableVisitor {
             syn::Pat::Type(pat_type) => {
                 self.visit_pat(&pat_type.pat);
             }
+            syn::Pat::Wild(_) => {
+                // Do nothing
+            }
```
Comment (MingweiSamuel) [inline stageleft_macro/src/quote_impl/free_variable/mod.rs:120]: That was easy

**Review by MingweiSamuel — APPROVED** [review]
